services:
  web:
    build: .
    image: cecilia
    develop:
      watch:
        - action: sync
          path: .
          target: /code
        - action: rebuild
          path: requirements.txt
          
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      db:
          condition: service_healthy
          restart: true
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=cecilia
      - MYSQL_DATABASE=cecilia
      - MYSQL_PASSWORD=12345
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
  mail:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
