# Generated by Django 4.2.11 on 2024-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('label_type', models.CharField(choices=[('INSTRUMENT', 'Instrument'), ('STEM', 'Stem'), ('SLEUTEL', 'Sleutel')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MusicPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.BinaryField()),
                ('labels', models.ManyToManyField(to='musicmix.label')),
            ],
        ),
    ]
