# Generated by Django 4.2.11 on 2024-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicmix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicpiece',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
