# Generated by Django 4.2.11 on 2024-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicmix', '0002_alter_musicpiece_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpiece',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
