# Generated by Django 5.0.6 on 2024-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicmix', '0006_alter_musicpiece_file_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
