# Generated by Django 5.0.7 on 2025-03-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicmix', '0007_passwordreset_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpiece',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
